<?php
    
    $linkTypes = array( "image"             => "Image",
                        "pdf"               => "PDF",
                        "href"              => "Link",
                        "href2"             => "Link 2",
                        "href3"             => "Link 3",
                        "video"             => "Video",
                        "videoyoutube"      => "YouTube",
                        "videovimeo"        => "Vimeo",
                        "buy"               => "Buy",
                        "buylinkshareapple" => "Buy From Apple",
                        "buyapple"          => "Buy From Apple",
                        "buyamazon"         => "Buy From Amazon",
                        "buyebay"           => "Buy From Ebay",
                        "appios"            => "iOS App",
                        "appmac"            => "Mac App",
                        "appwebos"          => "webOS App",
                        "appandroid"        => "Android App",
                        "appwindows"        => "Windows App",
                        "github"            => "GitHub",
                        "imdb"              => "IMDB Profile",
                        "espn"              => "ESPN Profile",
                        "webmd"             => "WebMD",
                        "manpage"           => "Documentation",
                        "twitter"           => "Twitter",
                        "linkedin"          => "LinkedIn",
                        "facebook"          => "Facebook",
                        "googleplus"        => "Google+",
                        "wikipedia"         => "Wikipedia",
                        "mediawiki"         => "MediaWiki",
                        "freebase"          => "Freebase",
                        "angellist"         => "AngelList",
                        "crunchbase"        => "CrunchBase",
                        "intelark"          => "Intel ARK",
                        "comicvine"         => "Comic Vine",
                        "annotation"        => "Annotation",
                        "map"               => "Map",
                        "mapgoogle"         => "Google Map",
                        "search"            => "Search",
                        "searchgoogle"      => "Google Search",
                        "searchyahoo"       => "Yahoo Search",
                        "searchbing"        => "Bing Search",
                        "searchpubmed"      => "PubMed Search",
                        "searchul"          => "Search Ultralinks",
                       );
    
?>
