<?php
    
    $linkTypes = array( "image"             => "Image",
                        "href"              => "Link",
                        "href2"             => "Link 2",
                        "href3"             => "Link 3",
                        "video"             => "Video",
                        "videoyoutube"      => "YouTube",
                        "buy"               => "Buy",
                        "buylinkshareapple" => "Buy From Apple",
                        "buyamazon"         => "Buy From Amazon",
                        "buyebay"           => "Buy From Ebay",
                        "appios"            => "iOS App",
                        "appmac"            => "Mac App",
                        "appwebos"          => "webOS App",
                        "appandroid"        => "Android App",
                        "appwindows"        => "Windows App",
                        "github"            => "GitHub",
                        "imdb"              => "IMDB Profile",
                        "manpage"           => "Documentation",
                        "twitter"           => "Twitter",
                        "linkedin"          => "LinkedIn",
                        "facebook"          => "Facebook",
                        "googleplus"        => "Google+",
                        "wikipedia"         => "Wikipedia",
                        "mediawiki"         => "MediaWiki",
                        "freebase"          => "Freebase",
                        "angellist"         => "AngelList",
                        "annotation"        => "Annotation",
                        "map"               => "Map",
                        "mapgoogle"         => "Google Map",
                        "search"            => "Search",
                        "searchgoogle"      => "Google Search",
                        "searchyahoo"       => "Yahoo Search",
                        "searchbing"        => "Bing Search",
                       );
    
?>
